### ISSUE TITLE
[Feature request] Specifying host SSH keys in config

### ISSUE THREAD

**Issue by MedicMomcilo** [rfrail3/keepconf#2]
It would be pretty useful if we could set SSH key file in the config for the host.
This can possibly aid in automation of defining hosts.

For example:
[main]
directory = /
max_size = 25M
rsync_user = root
rsync_key = /opt/ssh-secrets/server1-key.rsa

And then in the code just append it to ssh_rsync_opt when calling rsync.

I don't know how hard would it be to develop such an option.
It would be appreciated if you would take a look :)

Kind regards,
Momo.

**Comment by rfrail3** [comment]
Yes, let me a few days for think on it.

Thanks!

**Comment by rfrail3** [comment]
A tip: Please, use dev branch because it have the new release (wich is actually stable), the new feature will be there.

Note that in the new version, keepconf have a simple configuration. Only one .cfg file have the variables plus one more file with a simple list of hosts an an other with a simple list of files. All is documented in the manual.

**Comment by rfrail3** [comment]
Did you see the option "IdentityFile" available in ssh?.
For example, you can define a ~/.ssh/config file with something similar to:

```
Host server1
    HostName server1
    IdentityFile /opt/ssh-secrets/server1-key.rsa
```

Does it cover your case? If not, please, can you explain your particular scenario?

Thanks,

**Comment by rfrail3** [comment]
Hi momo,

Its done in "https://github.com/rfrail3/keepconf/tree/dev", now you can use "rsync_key" and "rsync_port".

I hope that this help you.

Regards,

**Comment by MedicMomcilo** [comment]
Wow... thank you so much for that speed :)
I really appreciate it.

I did knew about ~/.ssh/config but I wanted to have less points of failure.
As in, if I have dozens of hosts and something fails, I know to look at /etc/keepconf only.
Also distributing just one file per host seems pretty sleek.

I will re-consider both options (now that there are two :) )

Again, thanks and keep up the good work!
Momo.

**Comment by MedicMomcilo** [comment]
Hey Ricardo,

I was further looking into this implementation and it seems that either I don't understand development branch or it is not possible to define SSH key per host. Furthermore it seems that all per-host configuration is lost (I use this to organise and group hosts together).

Can you please correct me if I'm wrong?

Thanks in advance :)
Momo.

**Comment by rfrail3** [comment]
Hi Momo,

The new release 2.0 have a different approach in the configuration. If you don't have a common user + key for connect into the hosts, you need to create a .cfg file for each one plus an other file with a list of this particular host and define that in "list_hosts" variable.

You can put here your email and I will contact with you for help in the migration (I delete it after, sure).

Regards,

**Comment by MedicMomcilo** [comment]
Hi Ricardo,

Sorry for late reply, I was on vacation.
I would like to understand this new approach before I commit to it.
My mail is medicmomcilo@gmail.com.

Kind regards,
Momo.
