### ISSUE TITLE
File list converts to lowercase

### ISSUE THREAD

**Issue by MedicMomcilo** [rfrail3/keepconf#3]
Dear all,

I was trying to troubleshoot why I was getting 'Hosts not rsync'ed' and traced it back down to symlinks that point nowhere.
I wanted to exclude them but still got rsync errors. In verbose mode I found that initial list was converted to lowercase before it is fed to rsync.  You can test this by specifying anything with upper case letters (eg !/Somefile) and checking output of 'keepconf -v' it will say 'Exclude:  /somefile'  and the file in /tmp will contain same lowercased string.

I examined the code and it seems that it happens in 'extract_walk', but I am unable to pin-point where and to provide a patch.

Any help is appreciated.
Kind regards,
Momo.

**Comment by rfrail3** [comment]
Hi MedicMomcilo,

I just test it with the last version (2.0.0), only with a simple "/tmp/AAA" file and it keep the paths in uppercase, in the file passed to rsync are the paths in uppercase too:

...
INFO:Exclude: /tmp/AAA
INFO:Include: /tmp/AAA
INFO:Exclude paths: ['/tmp/AAA']->['/tmp/AAA']
INFO:Include paths: ['/tmp/AAA']->['/', '/tmp/', '/tmp/AAA']
...

Please, can you add more information?

Thanks,

**Comment by MedicMomcilo** [comment]
Hi Ricardo,

Sorry, I completely missed that you merged dev branch.
This is happening in older version, and I managed to track it down to ConfigParser and that optionxform should fix it, however that's where my expertise ends :)

I guess this is not applicable to new version.
You can go ahead and close this issue.

Kind regards,
Momo.

**Comment by rfrail3** [comment]
Ok, thanks!
