### ISSUE TITLE
questions on usage

### ISSUE THREAD

**Issue by mgaulton** [rfrail3/keepconf#4]
Loving the script but confused. Started off as a "how do I get a previous revision of this file" and I ran into the below. Wondering if you could clarify if i'm doing something incorrectly?

So I have the config set to commit True, local repo but when I go to the folder where the localhost is and issue a git status, it says no commits.

just for argument, i did a "git add *" and "git commit -m 'first'" to try and i get errors.
There are repos within the backed up folders but I'm not sure how to get around that.

server6:/home/keepconf/hosts # git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore
        localhost/

nothing added to commit but untracked files present (use "git add" to track)
server6:/home/keepconf/hosts # git add *
warning: adding embedded git repository: localhost/etc/apache2/custom.d/apache-ultimate-bad-bot-blocker
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> localhost/etc/apache2/custom.d/apache-ultimate-bad-bot-blocker
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached localhost/etc/apache2/custom.d/apache-ultimate-bad-bot-blocker
hint:
hint: See "git help submodule" for more information.

warning: adding embedded git repository: localhost/opt/code/Amsterdam
warning: adding embedded git repository: localhost/opt/code/RedditImageGrab
warning: adding embedded git repository: localhost/opt/code/deluge-labelplus
warning: adding embedded git repository: localhost/opt/code/docker-bro
warning: adding embedded git repository: localhost/opt/code/docker-snort
warning: adding embedded git repository: localhost/opt/code/dockerkippo/docker-kippo-graph
warning: adding embedded git repository: localhost/opt/code/dockerkippo/docker-kippo
warning: adding embedded git repository: localhost/opt/code/ipset-blacklist.original
warning: adding embedded git repository: localhost/opt/code/iptables
warning: adding embedded git repository: localhost/opt/code/kali-stuff
warning: adding embedded git repository: localhost/opt/code/torrent-cleaner
warning: adding embedded git repository: localhost/opt/ssh-find-agent
server6:/home/keepconf/hosts #

server6:/home/keepconf/hosts # git status
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule localhost/etc/apache2/custom.d/apache-ultimate-bad-bot-blocker
server6:/home/keepconf/hosts # git commit -m
error: switch `m' requires a value
server6:/home/keepconf/hosts # git commit -m 'first'
You have both localhost/opt/code/deluge-labelplus and localhost/opt/code/deluge-labelplus/LabelPlus.egg-info/PKG-INFO
You have both localhost/opt/code/deluge-labelplus and localhost/opt/code/deluge-labelplus/LabelPlus.egg-info/PKG-INFO
error: Error building trees
server6:/home/keepconf/hosts # git status
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule localhost/etc/apache2/custom.d/apache-ultimate-bad-bot-blocker

**Comment by rfrail3** [comment]
Hello,

Inside the configuration file, the "d_dest" variable points to the repo, what folder do you have defined?

You can try to execute keepconf with the "--verbose" option to see wat's going on under the hood.

**Comment by mgaulton** [comment]
its /home/keepconf for simplicity.
It just seems to barf because I have git repos in the folders i'm backing up.
